More easily create cache dir.
macmillancontentscience/dlr pull request #20
Opened 2022-09-20 18:57 UTC by jonthegeek

Closes #17.

2022-09-20 18:57 UTC, jonthegeek commented
I noticed that there was one other open issue, so we might as well close that out before sorting out a re-CRAN of this package.

2022-09-22 14:49 UTC, jonathanbratt requested changes
Found a typo. Otherwise looks good!

2022-09-22 14:49 UTC, jonathanbratt commented on R/path.R
> +      # good way to test the case where they directory exists but this user
```suggestion
      # good way to test the case where the directory exists but this user
```

2022-09-22 15:33 UTC, jonathanbratt approved these changes

2022-09-22 15:33 UTC, merged